services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sga
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red_interna

  backend:
    build:
      context: ./BE_API
      dockerfile: Dockerfile
    container_name: springboot-api
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sga
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    networks:
      - red_interna

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: flutter-web
    restart: always
    depends_on:
      - backend
    ports:
      - "8081:80"
    networks:
      - red_interna

volumes:
  mysql_data:

networks:
  red_interna:
    driver: bridge